name: Update Latest Projects

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch latest repos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "LATEST_PROJECTS"
          feed_list: "https://github.com/mansi-10-4.atom"
          max_post_count: "5"

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Updated latest projects section"
          git push
